services:
  peers_db:
    image: postgres:14
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - peers_db
    ports:
      - "8000:8000"

volumes:
  db_data:
